# Generated by Django 5.1 on 2025-05-24 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponto',
            options={},
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='profissional',
        ),
        migrations.AddField(
            model_name='ponto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterModelTable(
            name='ponto',
            table=None,
        ),
    ]
