# Generated by Django 5.1 on 2025-05-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_alter_ponto_options_remove_ponto_profissional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='nome_completo',
        ),
    ]
