# Generated by Django 5.1 on 2025-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_remove_profissional_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cargo',
            field=models.CharField(default='chefe', max_length=50, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_admissao',
            field=models.DateField(default='2025-05-12', verbose_name='Data de Admissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='gestor',
            field=models.CharField(default='Lucas', max_length=100, verbose_name='Nome do Gestor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=231231, max_digits=8, verbose_name='Remuneração'),
            preserve_default=False,
        ),
    ]
