# Generated by Django 5.1 on 2025-05-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gestor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Gestor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='remuneracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Remuneração'),
        ),
    ]
