# Generated by Django 5.1 on 2025-05-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_cargo_alter_usuario_data_admissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='remuneracao',
        ),
    ]
