# Generated by Django 5.1 on 2025-06-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='gestor',
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
