# Generated by Django 5.1 on 2025-06-17 20:38

import django.db.models.deletion
import ponto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='hora',
            field=models.TimeField(default=ponto.models.hora_truncada),
        ),
    ]
