# Generated by Django 5.1 on 2025-06-17 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_profissional_gestor_alter_registroponto_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL, verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
