# Generated by Django 5.1 on 2025-06-17 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_remove_profissional_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folhaponto',
            options={'verbose_name': 'Folha de Ponto', 'verbose_name_plural': 'Folhas de Ponto'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['criado_em'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['usuario__nome_completo'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['-data', '-hora'], 'verbose_name': 'Registro de Ponto', 'verbose_name_plural': 'Registros de Ponto'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='horario_entrada',
            field=models.TimeField(verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='horario_saida',
            field=models.TimeField(verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='intervalo_fim',
            field=models.TimeField(verbose_name='Fim do Intervalo'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='intervalo_inicio',
            field=models.TimeField(verbose_name='Início do Intervalo'),
        ),
        migrations.AlterUniqueTogether(
            name='folhaponto',
            unique_together={('profissional', 'mes', 'ano')},
        ),
    ]
