# Generated by Django 5.1 on 2025-06-17 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0006_alter_folhaponto_options_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='Lida?'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'destinatario', 'criado_em'], name='ponto_mensa_remeten_1fb295_idx'),
        ),
    ]
