# Generated by Django 5.1 on 2025-06-28 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0007_alter_mensagem_conteudo_alter_mensagem_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
